# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True


# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.12
